"use strict";
exports.__esModule = true;
var Radio_1 = require("./Radio");
var radio = new Radio_1.Radio();
radio.turnOn();
radio.tuneInStation(99.3);
radio.turnOff();
radio.turnOn();
radio.tuneInStation(100.9);
radio.turnOff();
radio.turnOff();
radio.tuneInStation(100.9);
radio.turnOn();
